config/routes.rb
Rails.application.routes.draw do
  #固定ページ設定
  root to: 'home#index'
  get '/about', to: 'home#about'
  get 'contact', to: 'home#contact'
  get 'howtouse', to: 'home#howto'
  get '/support', to: 'home#support'

  #ユーザープロフィール
  get '/profile', to: 'users#show'
  #Codeモデルに対するリソースルート生成
  resources :codes do
    collection do
      get 'ranking'
    end
    resources :likes, only: [:create]
    delete '/likes', to: 'likes#destroy', as: 'like'
    resources :comments, only: %i(create destroy)
  end
  #Twitter用のルーティング
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :code

  counter_culture :code

  validates :user_id, presence: true
  validates :code_id, presence: true
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate

  def create
    @code = Code.friendly.find(params[:code_id])
    unless @code.like?(current_user)
      @code.like(current_user, @code)
      @code.reload
      respond_to do |format|
        # リファラーとは、該当ページに遷移する直前に閲覧されていた参照元（遷移元・リンク元）ページのURL
        format.html { redirect_to request.referrer || root_url }
        format.js
      end
    end
  end

  def destroy
    @code = Code.friendly.find(params[:code_id])
    if @code.like?(current_user)
      @code.unlike(current_user)
      @code.reload
      respond_to do |format|
        format.html { redirect_to request.referrer || root_url }
        format.js
      end
    end
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<% if logged_in? %>


  <% if !current_user?(@code.user) %>
      <span class="like">
      <% if @code.like?(current_user) %>
        <%# 良いね済みであれば %>
        <%= form_with(model: @code.likes.find_by(user_id: current_user.id), url: code_like_path(@code.uuid), method: :delete, remote: true) do |f| %>
          <%= button_tag(class: "btn btn-default btn-xs") do %>
            <%= content_tag :span, "#{@code.likes_count}", class: "glyphicon glyphicon-heart" %>
          <% end %>
        <% end %>
      <% else %>
        <%# 良いね済みでなければ %>
        <%= form_with(model: @code.likes.build, url: code_likes_path(@code.uuid), remote: true) do |f| %>
          <div><%= hidden_field_tag :code_id, @code.id %></div>
          <%= button_tag(class: "btn btn-default btn-xs") do %>
            <%= content_tag :span, "#{@code.likes_count}", class: "glyphicon glyphicon-heart-empty" %>
          <% end %>
        <% end %>
      <% end %>
    </span>
  <% end %>

<% else %>

  <%= button_tag(class: "btn btn-default btn-xs") do %>
    <%= content_tag :span, "#{@code.likes_count}", class: "glyphicon glyphicon-heart-empty", id: "login-modal" %>
  <% end %>

  <div id="mask" class="hidden"></div>
  <div id="modal" class="hidden">
      <p>Twitterでのログインが必要です。</p>
      <div id="close">Close</div>
  </div>


  <script>
    let loginmodal = document.getElementById('login-modal');
    let mask = document.getElementById('mask');
    let modal = document.getElementById('modal');
    let close = document.getElementById('close');

    loginmodal.addEventListener('click', function(){
        modal.className = '';
        mask.className = '';
    });

    close.addEventListener('click', function(){
        modal.className = 'hidden';
        mask.className = 'hidden';
    });

    mask.addEventListener('click', function(){
        close.click();
    });
  </script>


<% end %>

app/views/likes/create.js.erb
$("#code-<%= @code.id %> .like").html("<%= escape_javascript(render 'likes/like', code: @code) %>");

app/views/likes/destroy.js.erb
$("#code-<%= @code.id %> .like").html("<%= escape_javascript(render 'likes/like', code: @code) %>");