config/routes.rb
Rails.application.routes.draw do
  #固定ページ設定
  root to: 'home#index'
  get '/about', to: 'home#about'
  get 'contact', to: 'home#contact'
  get 'howtouse', to: 'home#howto'
  get '/support', to: 'home#support'

  #ユーザープロフィール
  get '/profile', to: 'users#show'
  #Codeモデルに対するリソースルート生成
  resources :codes do
    collection do
      get 'ranking'
    end
    resources :likes, only: [:create]
    delete '/likes', to: 'likes#destroy', as: 'like'
    resources :comments, only: %i(create destroy)
  end
  #Twitter用のルーティング
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
end

app/views/partial/_footer.html.erb
<footer class="center">
  <p>Copyright©︎2018-<%= Date.today.year %> TwiCode All Right Reserved</p>
</footer>

app/views/partial/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/codes"><%= image_tag('twicode-logo.png', class: 'logo-image') %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/about">Twicodeって？</a></li>
        <li><a href="/howtouse">使い方</a></li>
        <li><a href="/contact">お問い合わせ</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <% if logged_in? %>
              <i class="glyphicon glyphicon-cog"></i>
            <% else %>
              使ってみる
            <% end %>
          <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% if !logged_in? %>
              <li><%= link_to 'コードを覗いてみる', codes_path %></li>
              <li><a href="/auth/twitter/">Twitterでログイン</a></li>
            <% else %>
              <li><%= link_to 'ログアウト', logout_path %></li>
              <li><%= link_to 'マイページ', profile_path %></li>
              <li><div data-turbolinks="false" class="no-turbolink"><%= link_to 'コードを作成する', new_code_path %></div></li>
              <li><%= link_to 'コード一覧', codes_path %></li>
            <% end %>
            <li role="separator" class="divider"></li>
            <li><a href="/support">開発者に恵みを与える</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>