config/routes.rb
Rails.application.routes.draw do
  #固定ページ設定
  root to: 'home#index'
  get '/about', to: 'home#about'
  get 'contact', to: 'home#contact'
  get 'howtouse', to: 'home#howto'
  get '/support', to: 'home#support'

  #ユーザープロフィール
  get '/profile', to: 'users#show'
  #Codeモデルに対するリソースルート生成
  resources :codes do
    collection do
      get 'ranking'
    end
    resources :likes, only: [:create]
    delete '/likes', to: 'likes#destroy', as: 'like'
    resources :comments, only: %i(create destroy)
  end
  #Twitter用のルーティング
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
end

app/models/code.rb
# == Schema Information
#
# Table name: codes
#
#  id          :integer          not null, primary key
#  filename    :string
#  description :string
#  body        :text
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  uuid        :string           default("b6bae27f-92f1-4523-875d-34e5f528f6ea"), not null
#  image_url   :string
#  likes_count :integer
#

class Code < ApplicationRecord
  #バリデーション
  validates :filename, presence: true
  mount_uploader :image_url, ImageUploader

  #active_storage
  has_one_attached :image_url

  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :like_users, through: :likes, source: :user

  # params[:id]にあたるスラッグをuuidに変更
  # Code.friendly.find(params[:id])のように検索
  extend FriendlyId
  friendly_id :uuid

  # 現在のユーザーがいいねしてたらtrueを返す
  def like?(user)
    like_users.include?(user)
  end

  # codeをいいねする
  def like(user, code)
    likes.create(user_id: user.id, code_id: code.id)
  end

  # codeのいいねを解除する
  def unlike(user)
    likes.find_by(user_id: user.id).destroy
  end
end

app/controllers/codes_controller.rb
class CodesController < ApplicationController

  def index
    @codes = Code.all
  end

  def show
    @code = Code.friendly.find(params[:id])
    # if @code.image_url.present?
    #   @image_url = @code.image_url.sub(/\.png/, '')
    # end
  end

  def new
    @code = current_user.codes.build
  end

  def create
    @code = current_user.codes.build(code_params)
    @code.uuid = SecureRandom.uuid
    if @code.save
      flash[:notice] = "コードを作成しました"
      redirect_to codes_url
    else
      flash[:notice] = "エラーが発生しました. もう一度保存して下さい。"
      render :new
    end
  end

  def edit
    @code = current_user.codes.friendly.find(params[:id])
  end

  def update
    @code = current_user.codes.friendly.find(params[:id])
    @code.update_attributes(code_params)   
    if @code.update(code_params)
      redirect_to code_url(@code)
    else
      render :edit
    end
  end

  def destroy
    flash[:notice] = 'コードファイルを削除しました。'
    @code = current_user.codes.friendly.find(params[:id])
    @code.destroy
    redirect_to :action => 'index'
  end


  def ranking
    @codes = Code.find(Like.group(:code_id).order('count(code_id) desc').limit(20).pluck(:code_id))
  end

    private

  def code_params
    params.require(:code).permit(%i(filename description body image_url))
  end

  def cut_path(url)
    url.sub(/\.\/public\/ogp\//, "")
  end

  def like(user)
    likes.create(user_id: user.id)
  end

  def unlike(user)
    likes.find_by(user_id: user.id).destroy
  end
end

app/helpers/codes_helper.rb
module CodesHelper
end

app/views/codes/edit.html.erb
<div class="container">
  <div class="center margin-top-wrapper">
      <%= form_with(model: @code, local: true) do |f| %>
        <div class="form-group">
          <%= f.text_field :filename, class: 'form-control', placeholder: 'Filename including extention...' %>
        </div>

        <div class="form-group">
          <%= f.text_field :description, class: 'form-control', placeholder: 'Summary of the code...' %>
        </div>

        <div class="panel panel-default">
          <div class="panel-heading">Code</div>
            <div class="form-group textarea-wrapper">
              <%= f.text_area :body, class: 'form-control textarea-body TabforbiddenTextArea' %>
            </div>
          </div>
        </div>
        <div class="center margin-bottom-wrapper">
          <div data-turbolinks="false" class="no-turbolink">
            <%= f.submit 'コードをアップデート', class: 'btn btn-success dropdown-toggle' %>
          </div>
        </div>
    <% end %>
  </div>
</div>
<script>
  // テキストエリア内でタブ移行を禁止するコード
  $(function(){
	$(".TabforbiddenTextArea").keydown(function(e){
    if (e.keyCode === 9) {
        e.preventDefault();
        var elem = e.target;
        var val = elem.value;
        var pos = elem.selectionStart;
        elem.value = val.substr(0, pos) + '\t' + val.substr(pos, val.length);
        elem.setSelectionRange(pos + 1, pos + 1);
      }
    });
  });
</script>

app/views/codes/index.html.erb
<div class="center margin-bottom-wrapper code-index-title">
  <i class="glyphicon glyphicon-console"></i> コード一覧
</div>
<div class="center margin-bottom-wrapper">
  <i class="glyphicon glyphicon-menu-down"></i>
</div>

<div class="container">
  <div class="center">
    <button class="center ranking-button"><a href="/codes/ranking">ランキングへ<i class="glyphicon glyphicon-stats"></i></a></button>
  </div>
  <% if !logged_in? %>
    <% @codes.last(5).reverse.each do |code| %>
      <div class="bs-callout bs-callout-info">
      <h4>
        <div data-turbolinks="false" class="no-turbolink">
        <%= link_to code.filename, code_path(code) %>
        </div>
      </h4>
      <p><%= code.description %></p>
      <img src="<%= code.user.image_url %>" class="user_profile_image_code_index"><span class="code-index-user-desc"><%= code.user.user_name %></span>
      </div>
    <% end %>
    <div class="continue center">
      <p>ログインすると、より多くの投稿が閲覧できます。</p>
      <div class="center">
        <button type="button" class="btn btn-info"><a href="/auth/twitter/">今すぐTwitterでログインする</a></button>
      </div>
    </div>
  <% else %>
    <% @codes.reverse.each do |code| %>
      <div class="bs-callout bs-callout-info">
      <h4><%= link_to code.filename, code_path(code) %></h4>
      <p><%= code.description %></p>
      <img src="<%= code.user.image_url %>" class="user_profile_image_code_index"><span class="code-index-user-desc"><%= code.user.user_name %></span>
      </div>
    <% end %>
  <% end %>
</div>

app/views/codes/new.html.erb
<div class="container">
  <div class="center margin-top-wrapper">
      <%= form_with(model: @code, local: true) do |f| %>
        <div class="form-group">
          <%= f.text_field :filename, class: 'form-control', placeholder: 'Filename including extention...' %>
        </div>

        <div class="form-group">
          <%= f.text_field :description, class: 'form-control', placeholder: 'Summary of the code...' %>
        </div>

        <div class="panel panel-default">
          <div class="panel-heading">Code</div>
            <div class="form-group textarea-wrapper">
              <%= f.text_area :body, class: 'form-control textarea-body TabforbiddenTextArea' %>
            </div>
          </div>
        </div>
        <div class="center margin-bottom-wrapper">
          <%= f.submit 'コードを作成', class: 'btn btn-success dropdown-toggle' %>
        </div>
    <% end %>
  </div>
</div>
<script>
  // テキストエリア内でタブ移行を禁止するコード
  $(function(){
	$(".TabforbiddenTextArea").keydown(function(e){
    if (e.keyCode === 9) {
        e.preventDefault();
        var elem = e.target;
        var val = elem.value;
        var pos = elem.selectionStart;
        elem.value = val.substr(0, pos) + '\t' + val.substr(pos, val.length);
        elem.setSelectionRange(pos + 1, pos + 1);
      }
    });
  });  
</script>

app/views/codes/ranking.html.erb
<div class="center margin-bottom-wrapper code-index-title">
  <i class="glyphicon glyphicon-console"></i> ランキング一覧
</div>
<div class="center margin-bottom-wrapper">
  <i class="glyphicon glyphicon-menu-down"></i>
</div>

<div class="container">
  <div class="center">
    <button class="center ranking-button"><a href="/codes/">最新投稿一覧へ<i class="glyphicon glyphicon-stats"></i></a></button>
  </div>
  <% if !logged_in? %>
    <% @codes.last(5).reverse.each do |code| %>
      <div class="bs-callout bs-callout-info">
      <h4>
        <div data-turbolinks="false" class="no-turbolink">
        <%= link_to code.filename, code_path(code) %>
        </div>
      </h4>
      <p><%= code.description %></p>
      <img src="<%= code.user.image_url %>" class="user_profile_image_code_index"><span class="code-index-user-desc"><%= code.user.user_name %></span>
      </div>
    <% end %>
    <div class="continue center">
      <p>ログインすると、より多くの投稿が閲覧できます。</p>
      <div class="center">
        <button type="button" class="btn btn-info"><a href="/auth/twitter/">今すぐTwitterでログインする</a></button>
      </div>
    </div>
  <% else %>
    <% @codes.reverse.each do |code| %>
      <div class="bs-callout bs-callout-info">
      <h4><%= link_to code.filename, code_path(code) %></h4>
      <p><%= code.description %></p>
      <img src="<%= code.user.image_url %>" class="user_profile_image_code_index"><span class="code-index-user-desc"><%= code.user.user_name %></span>
      </div>
    <% end %>
  <% end %>
</div>

app/views/codes/show.html.erb
<% content_for :ogp do %>
  <meta property="og:title" content="<%= @code.filename %>" />
  <meta property="og:type" content="article" />
  <meta property="og:url" content=<%= "https://twicode-share.herokuapp.com/codes/#{@code.uuid}" %> />
  <meta property="og:image" content="" />
  <meta property="og:site_name" content="TwiCode" />
  <meta property="og:description" content="<%= @code.description %>" />

  <!--twitterの設定-->
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:site" content=<%= "https://twicode-share.herokuapp.com/codes/#{@code.uuid}" %> />
  <meta name="twitter:image" content="" />
  <meta name="twitter:title" content="<%= @code.filename %>">
  <meta name="twitter:description" content="<%= @code.description %>" />
<% end %>

<div class="container">
  <div class="margin-top-wrapper">
    <div class="panel panel-info">
      <div class="panel-heading">ファイルの概要</div>
      <div class="panel-body">
        <%= @code.description %>
      </div>
    </div>

    <div class="center margin-bottom-wrapper">
      <i class="glyphicon glyphicon-chevron-down"></i>
    </div>

    <% if logged_in? %>
      <%# もしもコードユーザが自分なら %>
      <% if current_user.id == @code.user_id %>
      <ul class="nav nav-tabs">
        <li role="presentation" class="active"><a href="#">Code</a></li>
        <li role="presentation"><div data-turbolinks="false" class="no-turbolink"><%= link_to '編集', edit_code_path(@code) %></div></li>
      </ul>
      <% end %>
    <% end %>
    <div class="panel panel-default" id="tocanvas">
      <div class="panel-heading"><%= "<>#{@code.filename}.twicode" %></div>
        <div class="panel-body">
          <p><%= markdown(@code.body).html_safe %></p>

          <%# LikesコントローラではCodeのidが必要になるため、Likeビューをパーシャル化する際に、
          Codeをビューに渡してあげる必要がある。 %>
          <span id="code-<%= @code.id %>">
            <%= render "likes/like", locals: { code: @code } %>
          </span>

        </div>
      </div>
    </div>
  </div>

  <div class="center comment-center">
    <h5 class="comment-index">コメント一覧</h5>
      <% if @code.comments.nil? %>
        <div class="center">
          <p>まだコメントはありません</p>
        </div>
      <% else %>
        
        <% @code.comments.each do |c| %>
          <% if c.user == current_user %>
          <%# もしコメントが自分であれば、右寄せ %>
            <div class="comment container">
              <div class="comment-icon">
                <img src="<%= c.user.image_url %>">
                <p><%= c.user.user_name %></p>
              </div>
              <div class="chat">
                <div class="comment-description">
                  <%= link_to(content_tag(:i, '', class: 'glyphicon glyphicon-trash'), code_comment_path(@code, c), :method => :delete) %>
                  <p><%= c.content %></p>
                </div>
              </div>
            </div>
          <% else %>
          <%# 自分以外のコメントの場合 %>
            <div class="comment-other container" style="display: flex">
              <div class="comment-other-icon">
                <img src="<%= c.user.image_url %>">
                <p><%= c.user.user_name %></p>
              </div>
              <div class="chat-other">
                <div class="comment-other-description">
                  <p><%= c.content %></p>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
    
    <% if logged_in? %>
    <%# ログインユーザならばコメント可能 %>
    <div class="container">
      <h5>コメントする</h5>
        <%= form_with(model: @code.comments.build , local: true, url: code_comments_path(@code)) do |f| %>
          <div class="form-group">
            <%= f.text_field :content, class: 'form-control comment-write-box' %>
          </div>
          <%= f.submit 'コメントする', class: 'btn btn-success' %>
        <% end %>
      <% else %>
      <%# ログインユーザでなければコメント不可 %>
        <div class="alart">
          <p>ログインするとコメントできるようになります。</p>
        </div>
      <% end %>
    </div>
  </div>  
</div>

<%= form_with model: @code do |form| %>
  <%= form.file_field :image_url, type: 'hidden', value: '', id: 'imgform' %>
<% end %>

<%# 画像設定 %>
<div class="bg_wrapper-trans center">
  <div class="share-card">
    <div class="ogp-wrapper">
      <img src="" id="result" alt="<%= @code.filename %>" class="card-img" />
    </div>
    <div class="card-body">
      <h4><%= @code.filename %></h4>
      <p><%= @code.description %></p>
      <a href="https://twitter.com/share" class="twitter-share-button" data-show-count="false">Tweet</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
    </div>
  </div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/0.4.1/html2canvas.js"></script>
<script>
  //ロードされた際の処理として実施：
  window.onload = function(){
    //HTML内に画像を表示
    html2canvas(document.getElementById("tocanvas"),{
      onrendered: function(canvas){
        var imgData = canvas.toDataURL();
        document.getElementById("result").src = imgData;

        sendData = canvas.toDataURL("image/png");
        form = document.getElementById("imgform")
        form.value = sendData;
        form.submit();
      }
    });
  }
  function checkText() {
    //入力ボックスの内容を表示する
    alert( document.myform.imagedata.value );
  }
</script>

<% if logged_in? %>
  <% if current_user.id == @code.user_id %>
    <div class="center margin-bottom-wrapper">
      <button type="button" class="btn btn-danger"><%= link_to "<>#{@code.filename}.twicodeを削除", "/codes/#{@code.uuid}", method: :delete, data: { confirm: '本当に削除しますか？' } %></button>
    </div>
  <% end %>
<% end %>